### ISSUE TITLE
meta issues and queries

### ISSUE THREAD

**Issue by SusanBrown** [cwrc/ontology#242]
Many of these are not required for the Feb2018 milestone.

The following need to be checked by someone with internet connection

- [x] is bergamasque a form of drama?
- [x] is boutsRime a form of poetry?
- [x] is acrostic a form of poetry?
- [x] is oratoria a form of poetry and/or a song?
- [x] are dream visions always in verse?
- [x] should afterpiece have skos:broaderTerm pretext
- [x] Create an issue to create a performance category that would group drama and music and cabaret and ballet and film/tv script
- [x] should essay be a NT of scholarship?
- [x] is a harlequinade a NT of drama?
- [x] is a sketch a NT of drama?
- [x] might translation, sequel and answer be construed as paratexts?
- [x] make an issue to define Organization
- [x] make an issue to create music for grouping song and opera, and hymn
- [x] make an issue to create informational genres as a rough synonym for nonfictional (but noting that although the conveyance of specific content is a significant purpose, the contents may not be true, are vehicles for ideology like other texts, may have highly literary qualities, etc.) for things like documentary, cookbook, gardening book, review, government report, adventure writing, travel writing, exhibition catalogue, guidebook
- [x] make an issue to create story as related term to fiction and make it BT of  fabliau and legendFolktale (and reliable to legend or folktale) and parable and myth (which should perhaps be combined with legend/Folktale)
- [x] make an issue to consider creating a “descriptive genres" category for grouping pastoral lesbian, domestic, romance, didactic - basically a grouping that indicates categories that describe some aspect of the text’s content or purpose, broadly conceived
- [x] make an issue to consider creating a “formal genres” category for grouping together categories that indicate an aspect of format or formal characteristics, e.g. graphic novel, comic book, map, sketch book, scrap book, commonplace book, mixed media, anthology, notebook, multimedia, computer program, gift book, epistolary
- [x] what is “character”  (in genre) and shouldn’t it have a better label?
- [x] make an issue to discuss Property: cwrc:culturalFormTo. I have no idea what this means or what it would do.
- [x] do we need both Jacobism and Jacobinism? (probably comes down whether a distinction is supported in the instances)
- [x] create an issue titled Property: cwrc:literalForm
Proposed definition: This property indicates that a cwrc label has not been connected to a defined entity, so the literal value or string of words constitutes the label.

**Comment by SusanBrown** [comment]
@lemaka Please see the issue I just created for one of the outstanding queries here. Please do your best to answer the question and either make the changes as needed, ask someone else to make them if you can't, or pose followup questions.

**Comment by lemaka** [comment]
Right! Will also track down the issue you tagged me in and link back here.
