### ISSUE TITLE
Intertextuality Review

### ISSUE THREAD

**Issue by JasmineDW** [cwrc/ontology#533]
This issue tracks modifications to classes and predicates pertaining to the [Intertextuality tab](https://docs.google.com/spreadsheets/d/19h61m3maWIG50eR3dZzWlRx9TnGEGye4ZWKwu9bC9kc/edit#gid=0) of the Writing spreadsheet.
# Edits to be made
## [Line 23-24](https://docs.google.com/spreadsheets/d/19h61m3maWIG50eR3dZzWlRx9TnGEGye4ZWKwu9bC9kc/edit#gid=0&range=23:24)
- [x] cwrc:response - Remove rdfs:subPropertyOf:  cwrc:intertextualRelationship 
- [x] cwrc:responseRelationship - add rdfs:subPropertyOf: receptionRelationship; add cwrc:subjectCentricPredicate: cwrc:hasResponseRelationTo; remove cwrc:subjectCentricPredicate: cwrc:hasIntertextualRelationTo
- [x]  cwrc:relatesByResponseTo - replace with cwrc:hasResponseRelationTo; this is a SYMMETRIC PROPERTY (add rdf:type owl:SymmetricProperty); remove rdfs:subPropertyOf: cwrc:hasWritingRelationTo; add rdfs:subPropertyOf: cwrc:hasReceptionRelationTo; cwrc:hasIntertextualRelationTo

## [Line 27-36]
- [x] cwrc:RecentResponse - Rename to cwrc:LaterResponse; modify definition to: Indicates that a response to an author or one or more of their works occurred at some point after the initial response period.
- [x] cwrc:GenderedResponse - Modify definition to: Indicates a response that was influenced by gendered preconceptions.
- [x] cwrc:NonGendered - Change URI and Tag to cwrc:NonGenderedResponse; modify definition to: Indicates a response that was not influenced by genderered preconceptions.

## [Line 38-45]
- [x] cwrc:hasInfluenceOn, cwrc:isInfluencedBy, cwrc:influence - Update predicate definitions to include cwrc:Place, remove event as range
- [x] create cwrc:influencedBy Domain: cwrc:Person; org:organization; frbr:Work; cwrc:Event Range: cwrc:Person (Alliyya & Jasmine to do this together)
- [x] literaryInfluence, intellectualInfluence, familialInfluence - replace Parent Predicate with cwrc:influencedBy once this has been created in the ontology

# Tasks post edits
- [ ] @alliyya to generate diagram of subproperty graph of writing relationships and classes for to ensure edits make sense
