### ISSUE TITLE
Update links/graphs/queries in documentation

### ISSUE THREAD

**Issue by alliyya** [cwrc/ontology#563]
Tasks: 
- [x] Update all menu links to go to yasgui
- [ ] SPARQL Query Guide
- [ ] Intro to SPARQL
- [ ] Query Modifiers
- [ ] Sample Queries
- [x] Review available graphs from #543 and make sure the graphs exist with the correct data
- [ ] update content in [Our Dataset](https://sparql.cwrc.ca/testing/documentation/our-dataset.html)
- [ ] Push to testing
- [ ] Use Link checker tool to verify links after changes have been made
- [ ] Push to Prod

Related #543

**Comment by alliyya** [comment]
Not sure what was going on with Fuseki, but it's back up and working properly.

**Task 1:**

The currently available graphs are:


count | graph URI
-|-
1 | http://graph.lincsproject.ca/cwrc
2 | http://graph.lincsproject.ca/orlando
3 | http://graph.lincsproject.ca/orlando/1
4 | http://sparql.cwrc.ca/data/orlando
5 | http://sparql.cwrc.ca/data/orlando/bibliography
6 | http://sparql.cwrc.ca/data/orlando/biography
7 | http://sparql.cwrc.ca/data/orlando/simple
8 | http://sparql.cwrc.ca/data/orlando/simple/biography
9 | http://sparql.cwrc.ca/data/orlando/writing
10 | http://sparql.cwrc.ca/ontologies/cwrc
11 | http://sparql.cwrc.ca/ontologies/genre
12 | http://sparql.cwrc.ca/ontologies/ii
13 | http://vocab.lincsproject.ca/cwrc
14 | http://vocab.lincsproject.ca/eml
15 | http://vocab.lincsproject.ca/genre
16 | http://vocab.lincsproject.ca/ii

To do:
- [ ] delete: 1-3, 13-16 permanently
- [ ] clear all existing graphs and default 
- [ ] put up the ontologies
- [ ] the Orlando data
- [ ] Update the default graph.
